theme = "onedark"

[editor]
line-number = "relative"
mouse = false

[keys.insert]
"A-v" = [":insert-output echo '\\vec{}'", "collapse_selection"]
"A-r" = [":insert-output echo '\\mathbb{}'", "collapse_selection"]
